### ISSUE TITLE
Question about hardware requirements

### ISSUE THREAD

**Issue by lseventeen** [airvlab/cathsim#10]
Hi,

Thank you for presenting this excellent work. I would like to know the hardware requirements for running the code. My server has 128GB of memory, but it gets filled up after around 2000 training iterations. The memory usage gradually increases until the program crashes. Reducing the number of environments does not seem to solve the problem.

Are there any settings that can reduce memory usage?

<img width="1862" alt="微信图片_20231231131659" src="https://github.com/airvlab/cathsim/assets/48872641/53d3400a-536c-4327-81db-b89179698c45">

**Comment by tudorjnu** [comment]
This is weird. I've set `n_envs=n_cpus/2`. I've been running 6 environments on a 64GB RAM system. What is the number of environments selected?

**Comment by ghost** [comment]
@lseventeen Hi, I have the exact same problem, did you manage to resolve it in the end?

**Comment by tudorjnu** [comment]
It seems like there was something going on with the `_get_info()` function. I've made it optional and now it works accordingly. Sorry for this.
