### ISSUE TITLE
About loading images

### ISSUE THREAD

**Issue by ghost** [airvlab/cathsim#12]
Hi, thank you for such amazing work, I have a question regarding the code:

in shape_reconstruction.py:

    head_pos = DATA_DIR / f"{image_num}_geom_pos.npy"
    head_pos = np.load(head_pos)

    img1 = read_segmented_image(DATA_DIR / f"{image_num}_top.png")
    img2 = read_segmented_image(DATA_DIR / f"{image_num}_side.png")

I didn't see these files, are they generated after training?

Thank you in advance

**Comment by YuxuanWen-Code** [comment]
Also, these functions seem unreferenced.

from guidewire_reconstruction import (
    get_backbone_points,
    P_top,
    P_side,
    DATA_DIR,
    read_segmented_image,
    plot3d,
)

**Comment by Lisalsj** [comment]
May I ask if you have tried replacing the existing phantom?
