### ISSUE TITLE
Issue with running the unity_ar_vr_cathsim project build in Unity 

### ISSUE THREAD

**Issue by csudiptach** [airvlab/cathsim#3]
Hi there,

I have not been able to run the game environment on unity (from the directory unity_ar_vr_cathsim) for integration. However, the unity closes suddenly every time I try to run the build. 
I have seen similar problems faced by others over the internet but got no viable solution to it
I have reported the problem to unity and they have mentioned as the version of the actual project is made of 2019.4.0f1 version, they can not support versions older than 2022.3 other than 2020.3 LTS and 2021.3 LTS.
Could it be because of version issues or my laptop processor or GPU/graphics incompatibility with the .unity files of the project?

Please could you let me know how the team is able to fix this issue?

**Comment by vovantuan1999a** [comment]
Hi guys,
Let's me check and find out the solution for this issue.
Thank you.

**Comment by csudiptach** [comment]
Thank you so much. 
I truly appreciate it.

**Comment by vovantuan1999a** [comment]
Hi guys,

I have investigated the issue in my UnityHub, which is currently running version Unity Hub 3.4.2-beta.2 on Ubuntu. Within my UnityHub, I have the option to install any version through the "Installing" button.

Additionally, when importing any package, the Unity Hub notifies me if there is a version conflict, prompting me to install the correct version associated with the package.

Here's a helpful visual for reference:
![image](https://github.com/robotvisionlabs/cathsim/assets/43241986/11abb563-c7c2-4ee5-90d2-fb8dbb53ac4f)

Let me know if you have any questions or need further assistance.
Thank you

**Comment by tudorjnu** [comment]
Closing this as it appears to be sorted.
