### ISSUE TITLE
mujoco.FatalError: gladLoadGL error

### ISSUE THREAD

**Issue by XiangyuSha** [airvlab/cathsim#7]
Hi,

I think I've set and installed the environment successfully, but I encountered a issue when I tried to run (run_env) for manual control or training using (bash ./scripts/train.bash):

<img width="618" alt="Screenshot 2023-10-13 at 19 47 24" src="https://github.com/airvlab/cathsim/assets/109414968/ec74e1ae-f8fd-4ef0-88dc-540fbcef86dc">
<img width="619" alt="Screenshot 2023-10-13 at 20 05 20" src="https://github.com/airvlab/cathsim/assets/109414968/8103ca3d-fd8d-4b9c-a49e-7c3d7712ff6c">

It said there were and GLFWError and gladLoadGL error and I was confused. I searched online to look up for the similar issues (URL: https://github.com/Farama-Foundation/Gymnasium/issues/501)
Someone said it is that the GLFW library could be initialised but I still don't know how to solve it.

have any ideas on how to fix this?

**Comment by yz-lil** [comment]
same problem

**Comment by nqanh** [comment]
The training script `train.bash` and the `run_evn` can be run independently. 
I just installed on a fresh Ubuntu pc without any problems.

Try to re-install the `glfw` library?
`apt-get install libglfw3-dev`

**Comment by XiangyuSha** [comment]
Hi,

I think I did have glfw library and I re-installed it too.

<img width="645" alt="Screenshot 2023-10-21 at 12 36 06" src="https://github.com/airvlab/cathsim/assets/109414968/7b466cf0-e12b-4a88-9caf-221a6af86e1d">

But the same problem is still there. I don't think it's about the glfw. Could it be that we are running it on virtual machine, which is different from the real Ubuntu pc? I will try to run this in the real ubuntu pc in DIF lab later.

**Comment by yz-lil** [comment]
I turned on 3D acceleration in the VM configuration and checked my graphics driver configuration:
<img width="695" alt="截屏2023-10-21 12 55 51" src="https://github.com/airvlab/cathsim/assets/82555001/7a098ca6-1861-400e-b15e-f22456db08c9">
<img width="844" alt="截屏2023-10-21 12 56 09" src="https://github.com/airvlab/cathsim/assets/82555001/d8230271-6d01-46d4-b163-c8e21225e1e1">
<img width="1141" alt="截屏2023-10-21 12 56 32" src="https://github.com/airvlab/cathsim/assets/82555001/b5f5565d-ea1e-4ea8-af46-b5c015f54662">
<img width="812" alt="截屏2023-10-21 12 56 49" src="https://github.com/airvlab/cathsim/assets/82555001/68bbddd5-1769-4bce-987a-8b398d8cbaec">

These configurations appear to be normal, but the problem still exists.

**Comment by nqanh** [comment]
The `swrast_dri.so` seems to be missing from the system. We need it for `libGL` and rendering
https://askubuntu.com/questions/1352158/libgl-error-failed-to-load-drivers-iris-and-swrast-in-ubuntu-20-04

**Comment by yz-lil** [comment]
I re-installed swrast_dri.so and the problem is still not solved.
<img width="734" alt="截屏2023-10-21 13 14 35" src="https://github.com/airvlab/cathsim/assets/82555001/ef786e56-2181-493b-8bdf-e55b9476f8c4">

**Comment by nqanh** [comment]
can you paste the code/text of all the error message?

**Comment by yz-lil** [comment]
```
(cathsim) parallels@ubuntu-linux-22-04-desktop:~/cathsim$ run_env
libEGL warning: pci id for fd 10: 1ab8:0010, driver (null)

libEGL warning: MESA-LOADER: failed to open virtio_gpu: /usr/lib/dri/virtio_gpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/glfw/__init__.py:916: GLFWError: (65542) b'EGL: Failed to initialize EGL: EGL is not or could not be initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "/home/parallels/.miniconda3/envs/cathsim/bin/run_env", line 8, in <module>
    sys.exit(cmd_run_env())
  File "/home/parallels/cathsim/src/cathsim/console.py", line 140, in cmd_run_env
    env = make_dm_env(
  File "/home/parallels/cathsim/src/cathsim/dm/env.py", line 639, in make_dm_env
    env = composer.Environment(
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/composer/environment.py", line 333, in __init__
    super().__init__(
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/composer/environment.py", line 226, in __init__
    self._recompile_physics_and_update_observables()
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/composer/environment.py", line 248, in _recompile_physics_and_update_observables
    self._observation_updater.reset(self._physics_proxy, self._random_state)
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/composer/observation/updater.py", line 165, in reset
    enabled.observation_callable())
  File "/home/parallels/cathsim/src/cathsim/dm/observables.py", line 60, in get_image
    image = physics.render(
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 223, in render
    camera = Camera(
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 711, in __init__
    if self._physics.contexts.mujoco is not None:
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 533, in contexts
    self._make_rendering_contexts()
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/mujoco/engine.py", line 519, in _make_rendering_contexts
    mujoco_context = wrapper.MjrContext(self.model, render_context)
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/mujoco/wrapper/core.py", line 603, in __init__
    ptr = ctx.call(mujoco.MjrContext, model.ptr, font_scale)
  File "/home/parallels/.miniconda3/envs/cathsim/lib/python3.9/site-packages/dm_control/_render/executor/render_executor.py", line 138, in call
    return func(*args, **kwargs)
mujoco.FatalError: gladLoadGL error
```

**Comment by yz-lil** [comment]
I've searched for some ways to do this, maybe there is something wrong with the echo $LD_LIBRARY_PATH configuration? My LD_LIBRARY_PATH is empty, do I need to export anything?
<img width="724" alt="截屏2023-10-22 13 40 26" src="https://github.com/airvlab/cathsim/assets/82555001/ed14f1cf-9c2e-48e6-a9b3-9d8d285d6852">

**Comment by nqanh** [comment]
Both the two libs can't be found:

```
libEGL warning: MESA-LOADER: failed to open virtio_gpu: /usr/lib/dri/virtio_gpu_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)

libEGL warning: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/aarch64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
```

Check if they are installed? if yes, try to add them to the $LD_LIBRARY_PATH and source the bash file.

**Comment by yz-lil** [comment]
I don't know why it's still wrong, I also completed all the updates (`sudo apt update`, `sudo apt install libgl1-mesa-dri.` and `sudo apt-get install libglfw3-dev`)
<img width="728" alt="截屏2023-10-22 16 00 07" src="https://github.com/airvlab/cathsim/assets/82555001/4522e4fe-86a9-4cfe-9990-5c8e97b4a4cf">
<img width="730" alt="截屏2023-10-22 16 02 03" src="https://github.com/airvlab/cathsim/assets/82555001/09a978a0-7f0d-43d5-9358-90ff5c6bf974">

**Comment by tudorjnu** [comment]
The issue is not from here but from MuJoCo itself. Please consult the issues in MuJoCo's repo [here](https://github.com/google-deepmind/mujoco).

In your case, it is an issue with the VM. Have you added the library to `.bashrc`?

**Comment by tudorjnu** [comment]
Never mind, seems like the issue was with `mujoco` updating to `3.0.0` from `2.1.7`. Issue should be now resolved.

**Comment by fromWRF** [comment]
> Hi,
> 
> I think I did have glfw library and I re-installed it too.
> 
> <img alt="Screenshot 2023-10-21 at 12 36 06" width="645" src="https://private-user-images.githubusercontent.com/109414968/277105736-7b466cf0-e12b-4a88-9caf-221a6af86e1d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzc3MzgyMzAsIm5iZiI6MTczNzczNzkzMCwicGF0aCI6Ii8xMDk0MTQ5NjgvMjc3MTA1NzM2LTdiNDY2Y2YwLWUxMmItNGE4OC05Y2FmLTIyMWE2YWY4NmUxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyNFQxNjU4NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjdkMDYwNWNkOTk1ODI1ZWYxZDM2ODU3NWZhNzI4YWE5MTMxMDMzYTM5MDBlNGI1YjAyZjNlYzlhM2E3NGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yk_vvpWaonswT_AJPjtBtAjpCUnF-SrjamypojGnbgU">
> But the same problem is still there. I don't think it's about the glfw. Could it be that we are running it on virtual machine, which is different from the real Ubuntu pc? I will try to run this in the real ubuntu pc in DIF lab later.

Do you successfully run this in real ubuntuc pc?
