### ISSUE TITLE
Incorrect Procedure Portrayal

### ISSUE THREAD

**Issue by cyrilzakka** [airvlab/cathsim#8]
Hello, this looks like great work but there seems to be an issue with your methodology. In most catheterization procedure, we enter the patient from the femoral artery, and eventually end up in the descending aorta and not the ascending aorta as portrayed in all your repo media.

**Comment by tudorjnu** [comment]
Hello @cyrilzakka. Thank you for raising the issue. Indeed that is correct and the current version is using the descending aorta (as seen in the [path comparison](https://github.com/airvlab/cathsim#path-comparison) part). I will have to change the figure eventually.
