### ISSUE TITLE
Question about the number of revolute joints

### ISSUE THREAD

**Issue by zhuyinheng** [airvlab/cathsim#9]
From the following code snippet, the number of revolute joint is 1:
https://github.com/airvlab/cathsim/blob/9aa73bd72dfe41e1558484df4ecbbeb0bc6bb4f6/src/cathsim/dm/components/guidewire.py#L145C1-L156C1

However, in the paper, it states:
> **the first 20 elements are associated with motors that actuate the revolute joints inside the tip** of the catheter plus the prismatic joint responsible for the translational movement.

And my questions are: what's the total number revolute joints?
More specifically, according to the implementation, it's a normal guidewire actuator model, where operator can only push, pull and rotate. 
According to the paper, it's a "advanced" guidewire actuator model, where the operator can control the push/pull as well as changing the shape of tip (by rotate the 20 revolute joints). Is it possiblable in the real-world? can you providing any reference allowing controlling the tip shape inside vessel?

**Comment by tudorjnu** [comment]
> what's the total number revolute joints? More specifically, according to the implementation, it's a normal guidewire actuator model, where operator can only push, pull and rotate.

The current iteration takes into account translation (push & pull) and rotation. Yes, that is correct, the current implementation abides the guidewire specs as apparent in the operating theater.

> According to the paper, it's a "advanced" guidewire actuator model, where the operator can control the push/pull as well as changing the shape of tip (by rotate the 20 revolute joints). Is it possiblable in the real-world? can you providing any reference allowing controlling the tip shape inside vessel?

This implementation aimed to give the agent more control over the actuation mechanism. An example could be [this](https://ieeexplore.ieee.org/abstract/document/10173658). However, agents can actuate joints independently, whereas humans cannot.
